Repository allnes/MPI_Practical_Course, pull requests merged in 2018-11, with the labels that each got.

#53 Устранение ошибок в задаче 1.
  modules/task_1/Zolotareva_Olesya_task1_MiddleValueVect/main.cpp
Labels: bug

#56 Вдовин Евгений. Задача 1. Правки
  modules/task_1/Vdovin_Eugene_task1_NumWords/main.cpp
Labels: bug

#58 Added experimental scalar multiplication
  .travis.yml
  appveyor.yml
  modules/CMakeLists.txt
  modules/experimental/CMakeLists.txt
  modules/experimental/scalar_multiplication/CMakeLists.txt
  modules/experimental/scalar_multiplication/main.cpp
  scripts/lint.py
Labels: duplicate

#62 Added opencv (TravisCI)
  .travis.yml
  appveyor.yml
Labels: wontfix

#61 Перов Дима. Задача 2. Производители-потребители.
  .travis.yml
  appveyor.yml
  modules/task_2/CMakeLists.txt
  modules/task_2/Perov_Dima_task2_ProducerConsumer/CMakeLists.txt
  modules/task_2/Perov_Dima_task2_ProducerConsumer/main.cpp
Labels: enhancement

#64 Not use opencv (Appveyore)
  appveyor.yml
Labels: wontfix

#63 Вдовин Евгений. Задача 2. Читатели-писатели.
  .travis.yml
  appveyor.yml
  modules/task_2/CMakeLists.txt
  modules/task_2/Vdovin_Eugene_task2_Readers_and_Writers/CMakeLists.txt
  modules/task_2/Vdovin_Eugene_task2_Readers_and_Writers/main.cpp
Labels: enhancement

#67 Репин Владимир. Задача 2. Метод Гаусса-Жордана.
  .travis.yml
  appveyor.yml
  modules/task_2/CMakeLists.txt
  modules/task_2/Repin_Vladimir_Gaussian_Elimination/CMakeLists.txt
  modules/task_2/Repin_Vladimir_Gaussian_Elimination/main.cpp
Labels: enhancement

#66 Яковлев Павел. Задача 2. Умножение матрицы на вектор, вертикальная ленточная схема.
  .travis.yml
  appveyor.yml
  modules/task_2/CMakeLists.txt
  modules/task_2/Yakovlev_Pavel_mul_matr_vect/CMakeLists.txt
  modules/task_2/Yakovlev_Pavel_mul_matr_vect/main.cpp
Labels: enhancement

#69 Вихрев Иван. Задача 2. Сглаживание изображения.
  .travis.yml
  modules/task_2/CMakeLists.txt
  modules/task_2/Vikhrev_Ivan_task2_ImageProcessing/CMakeLists.txt
  modules/task_2/Vikhrev_Ivan_task2_ImageProcessing/main.cpp
Labels: enhancement

#72 Yunin Ivan Task 2 Multiplication matrix vector (division on tapes)
  .travis.yml
  appveyor.yml
  modules/task_1/Yunin_Ivan_maximum_elem_vector/main.cpp
  modules/task_2/CMakeLists.txt
  modules/task_2/Yunin_Ivan_task2_mult_matrix_vector_div_on_tapes/CMakeLists.txt
  modules/task_2/Yunin_Ivan_task2_mult_matrix_vector_div_on_tapes/main.cpp
Labels: enhancement

#74 Task 2. Druzhinin Alexei. Matrix multiplication (One horizontal, the second vertical)
  .travis.yml
  appveyor.yml
  modules/task_2/CMakeLists.txt
  modules/task_2/Druzhinin_Alexei_mul_matrix/CMakeLists.txt
  modules/task_2/Druzhinin_Alexei_mul_matrix/main.cpp
Labels: enhancement

#73 Danilov N. Task 2: Message passing via ring topology.
  .travis.yml
  appveyor.yml
  modules/task_2/CMakeLists.txt
  modules/task_2/ndanilov_topologies/CMakeLists.txt
  modules/task_2/ndanilov_topologies/host.cpp
  modules/task_2/ndanilov_topologies/include/host.h
  modules/task_2/ndanilov_topologies/include/packet.h
  modules/task_2/ndanilov_topologies/main.cpp
Labels: enhancement

#78 Task 2. Druzhinin Alexei. Multiply matrixes
  modules/task_2/Druzhinin_Alexei_mul_matrix/main.cpp
Labels: bug, enhancement

#81 Яковлев Павел. Задача 2. Баг фикс
  modules/task_2/Yakovlev_Pavel_mul_matr_vect/main.cpp
Labels: enhancement

#83 Task 2. Ivan Yunin. Time metering changed.
  modules/task_2/Yunin_Ivan_task2_mult_matrix_vector_div_on_tapes/main.cpp
Labels: bug

#84 Вихрев. Обработка изображения с веб-камеры.
  modules/task_2/Vikhrev_Ivan_task2_ImageProcessing/main.cpp
Labels: enhancement
